// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: annual_transactions.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAnnualTransaction = `-- name: CreateAnnualTransaction :one
INSERT INTO annual_transactions (
    user_id,
    name,
    value,
    day,
    month,
    category_id,
    credit_card_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, user_id, name, value, day, month, category_id, credit_card_id, created_at, updated_at
`

type CreateAnnualTransactionParams struct {
	UserID       uuid.UUID      `json:"user_id"`
	Name         string         `json:"name"`
	Value        pgtype.Numeric `json:"value"`
	Day          int32          `json:"day"`
	Month        int32          `json:"month"`
	CategoryID   uuid.UUID      `json:"category_id"`
	CreditCardID pgtype.UUID    `json:"credit_card_id"`
}

func (q *Queries) CreateAnnualTransaction(ctx context.Context, arg CreateAnnualTransactionParams) (AnnualTransaction, error) {
	row := q.db.QueryRow(ctx, createAnnualTransaction,
		arg.UserID,
		arg.Name,
		arg.Value,
		arg.Day,
		arg.Month,
		arg.CategoryID,
		arg.CreditCardID,
	)
	var i AnnualTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Value,
		&i.Day,
		&i.Month,
		&i.CategoryID,
		&i.CreditCardID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAnnualTransaction = `-- name: DeleteAnnualTransaction :exec
DELETE FROM annual_transactions
WHERE id = $1
`

func (q *Queries) DeleteAnnualTransaction(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAnnualTransaction, id)
	return err
}

const getAnnualTransactionByID = `-- name: GetAnnualTransactionByID :one
SELECT 
    at.id,
    at.user_id, 
    at.name, 
    at.value,
    at.day, 
    at.month,
    at.created_at, 
    at.updated_at,

    c.id as category_id, 
    c.transaction_type as category_transaction_type, 
    c.name as category_name, 
    c.icon as category_icon,
    c.created_at as category_created_at, 
    c.updated_at as category_updated_at,

    cc.id as creditcard_id, 
    cc.name as creditcard_name, 
    cc.first_four_numbers as creditcard_first_four_numbers, 
    cc.credit_limit as creditcard_credit_limit, 
    cc.close_day as creditcard_close_day, 
    cc.expire_day as creditcard_expire_day, 
    cc.background_color as creditcard_background_color, 
    cc.text_color as creditcard_text_color,
    cc.created_at as creditcard_created_at, 
    cc.updated_at as creditcard_updated_at
FROM annual_transactions at
LEFT JOIN categories c ON at.category_id = c.id
LEFT JOIN credit_cards cc ON at.credit_card_id = cc.id
WHERE at.id = $1
`

type GetAnnualTransactionByIDRow struct {
	ID                         uuid.UUID          `json:"id"`
	UserID                     uuid.UUID          `json:"user_id"`
	Name                       string             `json:"name"`
	Value                      pgtype.Numeric     `json:"value"`
	Day                        int32              `json:"day"`
	Month                      int32              `json:"month"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	CategoryID                 pgtype.UUID        `json:"category_id"`
	CategoryTransactionType    pgtype.Int4        `json:"category_transaction_type"`
	CategoryName               pgtype.Text        `json:"category_name"`
	CategoryIcon               pgtype.Text        `json:"category_icon"`
	CategoryCreatedAt          pgtype.Timestamptz `json:"category_created_at"`
	CategoryUpdatedAt          pgtype.Timestamptz `json:"category_updated_at"`
	CreditcardID               pgtype.UUID        `json:"creditcard_id"`
	CreditcardName             pgtype.Text        `json:"creditcard_name"`
	CreditcardFirstFourNumbers pgtype.Text        `json:"creditcard_first_four_numbers"`
	CreditcardCreditLimit      pgtype.Float8      `json:"creditcard_credit_limit"`
	CreditcardCloseDay         pgtype.Int4        `json:"creditcard_close_day"`
	CreditcardExpireDay        pgtype.Int4        `json:"creditcard_expire_day"`
	CreditcardBackgroundColor  pgtype.Text        `json:"creditcard_background_color"`
	CreditcardTextColor        pgtype.Text        `json:"creditcard_text_color"`
	CreditcardCreatedAt        pgtype.Timestamptz `json:"creditcard_created_at"`
	CreditcardUpdatedAt        pgtype.Timestamptz `json:"creditcard_updated_at"`
}

func (q *Queries) GetAnnualTransactionByID(ctx context.Context, id uuid.UUID) (GetAnnualTransactionByIDRow, error) {
	row := q.db.QueryRow(ctx, getAnnualTransactionByID, id)
	var i GetAnnualTransactionByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Value,
		&i.Day,
		&i.Month,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryID,
		&i.CategoryTransactionType,
		&i.CategoryName,
		&i.CategoryIcon,
		&i.CategoryCreatedAt,
		&i.CategoryUpdatedAt,
		&i.CreditcardID,
		&i.CreditcardName,
		&i.CreditcardFirstFourNumbers,
		&i.CreditcardCreditLimit,
		&i.CreditcardCloseDay,
		&i.CreditcardExpireDay,
		&i.CreditcardBackgroundColor,
		&i.CreditcardTextColor,
		&i.CreditcardCreatedAt,
		&i.CreditcardUpdatedAt,
	)
	return i, err
}

const getShortAnnualTransactionByID = `-- name: GetShortAnnualTransactionByID :one
SELECT id, user_id, name, value, day, month, category_id, credit_card_id, created_at, updated_at
FROM annual_transactions
WHERE id = $1
`

func (q *Queries) GetShortAnnualTransactionByID(ctx context.Context, id uuid.UUID) (AnnualTransaction, error) {
	row := q.db.QueryRow(ctx, getShortAnnualTransactionByID, id)
	var i AnnualTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Value,
		&i.Day,
		&i.Month,
		&i.CategoryID,
		&i.CreditCardID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAnnualTransactionsByUserIDPaginated = `-- name: ListAnnualTransactionsByUserIDPaginated :many
SELECT 
    at.id,
    at.user_id, 
    at.name, 
    at.value,
    at.day, 
    at.month,
    at.created_at, 
    at.updated_at,

    c.id as category_id, 
    c.transaction_type as category_transaction_type, 
    c.name as category_name, 
    c.icon as category_icon,
    c.created_at as category_created_at, 
    c.updated_at as category_updated_at,

    cc.id as creditcard_id, 
    cc.name as creditcard_name, 
    cc.first_four_numbers as creditcard_first_four_numbers, 
    cc.credit_limit as creditcard_credit_limit, 
    cc.close_day as creditcard_close_day, 
    cc.expire_day as creditcard_expire_day, 
    cc.background_color as creditcard_background_color, 
    cc.text_color as creditcard_text_color,
    cc.created_at as creditcard_created_at, 
    cc.updated_at as creditcard_updated_at,

    COUNT(*) OVER() as total_count
FROM annual_transactions at
LEFT JOIN categories c ON at.category_id = c.id
LEFT JOIN credit_cards cc ON at.credit_card_id = cc.id
WHERE at.user_id = $1
ORDER BY at.month ASC, at.day ASC
LIMIT $2 OFFSET $3
`

type ListAnnualTransactionsByUserIDPaginatedParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListAnnualTransactionsByUserIDPaginatedRow struct {
	ID                         uuid.UUID          `json:"id"`
	UserID                     uuid.UUID          `json:"user_id"`
	Name                       string             `json:"name"`
	Value                      pgtype.Numeric     `json:"value"`
	Day                        int32              `json:"day"`
	Month                      int32              `json:"month"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	CategoryID                 pgtype.UUID        `json:"category_id"`
	CategoryTransactionType    pgtype.Int4        `json:"category_transaction_type"`
	CategoryName               pgtype.Text        `json:"category_name"`
	CategoryIcon               pgtype.Text        `json:"category_icon"`
	CategoryCreatedAt          pgtype.Timestamptz `json:"category_created_at"`
	CategoryUpdatedAt          pgtype.Timestamptz `json:"category_updated_at"`
	CreditcardID               pgtype.UUID        `json:"creditcard_id"`
	CreditcardName             pgtype.Text        `json:"creditcard_name"`
	CreditcardFirstFourNumbers pgtype.Text        `json:"creditcard_first_four_numbers"`
	CreditcardCreditLimit      pgtype.Float8      `json:"creditcard_credit_limit"`
	CreditcardCloseDay         pgtype.Int4        `json:"creditcard_close_day"`
	CreditcardExpireDay        pgtype.Int4        `json:"creditcard_expire_day"`
	CreditcardBackgroundColor  pgtype.Text        `json:"creditcard_background_color"`
	CreditcardTextColor        pgtype.Text        `json:"creditcard_text_color"`
	CreditcardCreatedAt        pgtype.Timestamptz `json:"creditcard_created_at"`
	CreditcardUpdatedAt        pgtype.Timestamptz `json:"creditcard_updated_at"`
	TotalCount                 int64              `json:"total_count"`
}

func (q *Queries) ListAnnualTransactionsByUserIDPaginated(ctx context.Context, arg ListAnnualTransactionsByUserIDPaginatedParams) ([]ListAnnualTransactionsByUserIDPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listAnnualTransactionsByUserIDPaginated, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAnnualTransactionsByUserIDPaginatedRow
	for rows.Next() {
		var i ListAnnualTransactionsByUserIDPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Value,
			&i.Day,
			&i.Month,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryID,
			&i.CategoryTransactionType,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.CategoryCreatedAt,
			&i.CategoryUpdatedAt,
			&i.CreditcardID,
			&i.CreditcardName,
			&i.CreditcardFirstFourNumbers,
			&i.CreditcardCreditLimit,
			&i.CreditcardCloseDay,
			&i.CreditcardExpireDay,
			&i.CreditcardBackgroundColor,
			&i.CreditcardTextColor,
			&i.CreditcardCreatedAt,
			&i.CreditcardUpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnnualTransaction = `-- name: UpdateAnnualTransaction :one
UPDATE annual_transactions
SET
    name = $2,
    value = $3,
    day = $4,
    month = $5,
    category_id = $6,
    credit_card_id = $7,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, value, day, month, category_id, credit_card_id, created_at, updated_at
`

type UpdateAnnualTransactionParams struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	Value        pgtype.Numeric `json:"value"`
	Day          int32          `json:"day"`
	Month        int32          `json:"month"`
	CategoryID   uuid.UUID      `json:"category_id"`
	CreditCardID pgtype.UUID    `json:"credit_card_id"`
}

func (q *Queries) UpdateAnnualTransaction(ctx context.Context, arg UpdateAnnualTransactionParams) (AnnualTransaction, error) {
	row := q.db.QueryRow(ctx, updateAnnualTransaction,
		arg.ID,
		arg.Name,
		arg.Value,
		arg.Day,
		arg.Month,
		arg.CategoryID,
		arg.CreditCardID,
	)
	var i AnnualTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Value,
		&i.Day,
		&i.Month,
		&i.CategoryID,
		&i.CreditCardID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
