// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: installment_transaction.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createInstallmentTransaction = `-- name: CreateInstallmentTransaction :one
INSERT INTO installment_transactions (
    user_id,
    name,
    value,
    initial_date,
    final_date,
    category_id,
    credit_card_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, user_id, name, value, initial_date, final_date, category_id, credit_card_id, created_at, updated_at
`

type CreateInstallmentTransactionParams struct {
	UserID       uuid.UUID          `json:"user_id"`
	Name         string             `json:"name"`
	Value        pgtype.Numeric     `json:"value"`
	InitialDate  pgtype.Timestamptz `json:"initial_date"`
	FinalDate    pgtype.Timestamptz `json:"final_date"`
	CategoryID   uuid.UUID          `json:"category_id"`
	CreditCardID pgtype.UUID        `json:"credit_card_id"`
}

func (q *Queries) CreateInstallmentTransaction(ctx context.Context, arg CreateInstallmentTransactionParams) (InstallmentTransaction, error) {
	row := q.db.QueryRow(ctx, createInstallmentTransaction,
		arg.UserID,
		arg.Name,
		arg.Value,
		arg.InitialDate,
		arg.FinalDate,
		arg.CategoryID,
		arg.CreditCardID,
	)
	var i InstallmentTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Value,
		&i.InitialDate,
		&i.FinalDate,
		&i.CategoryID,
		&i.CreditCardID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInstallmentTransaction = `-- name: DeleteInstallmentTransaction :exec
DELETE FROM installment_transactions
WHERE id = $1
`

func (q *Queries) DeleteInstallmentTransaction(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInstallmentTransaction, id)
	return err
}

const getInstallmentTransactionByID = `-- name: GetInstallmentTransactionByID :one
SELECT 
    it.id,
    it.user_id, 
    it.name, 
    it.value,
    it.initial_date, 
    it.final_date,
    it.created_at, 
    it.updated_at,

    c.id as category_id, 
    c.transaction_type as category_transaction_type, 
    c.name as category_name, 
    c.icon as category_icon,
    c.created_at as category_created_at,
    c.updated_at as category_updated_at,

    cc.id as creditcard_id, 
    cc.name as creditcard_name, 
    cc.first_four_numbers as creditcard_first_four_numbers, 
    cc.credit_limit as creditcard_credit_limit, 
    cc.close_day as creditcard_close_day, 
    cc.expire_day as creditcard_expire_day, 
    cc.background_color as creditcard_background_color, 
    cc.text_color as creditcard_text_color,
    cc.created_at as creditcard_created_at,
    cc.updated_at as creditcard_updated_at
FROM installment_transactions it
LEFT JOIN categories c ON it.category_id = c.id
LEFT JOIN credit_cards cc ON it.credit_card_id = cc.id
WHERE it.id = $1
`

type GetInstallmentTransactionByIDRow struct {
	ID                         uuid.UUID          `json:"id"`
	UserID                     uuid.UUID          `json:"user_id"`
	Name                       string             `json:"name"`
	Value                      pgtype.Numeric     `json:"value"`
	InitialDate                pgtype.Timestamptz `json:"initial_date"`
	FinalDate                  pgtype.Timestamptz `json:"final_date"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	CategoryID                 pgtype.UUID        `json:"category_id"`
	CategoryTransactionType    pgtype.Int4        `json:"category_transaction_type"`
	CategoryName               pgtype.Text        `json:"category_name"`
	CategoryIcon               pgtype.Text        `json:"category_icon"`
	CategoryCreatedAt          pgtype.Timestamptz `json:"category_created_at"`
	CategoryUpdatedAt          pgtype.Timestamptz `json:"category_updated_at"`
	CreditcardID               pgtype.UUID        `json:"creditcard_id"`
	CreditcardName             pgtype.Text        `json:"creditcard_name"`
	CreditcardFirstFourNumbers pgtype.Text        `json:"creditcard_first_four_numbers"`
	CreditcardCreditLimit      pgtype.Float8      `json:"creditcard_credit_limit"`
	CreditcardCloseDay         pgtype.Int4        `json:"creditcard_close_day"`
	CreditcardExpireDay        pgtype.Int4        `json:"creditcard_expire_day"`
	CreditcardBackgroundColor  pgtype.Text        `json:"creditcard_background_color"`
	CreditcardTextColor        pgtype.Text        `json:"creditcard_text_color"`
	CreditcardCreatedAt        pgtype.Timestamptz `json:"creditcard_created_at"`
	CreditcardUpdatedAt        pgtype.Timestamptz `json:"creditcard_updated_at"`
}

func (q *Queries) GetInstallmentTransactionByID(ctx context.Context, id uuid.UUID) (GetInstallmentTransactionByIDRow, error) {
	row := q.db.QueryRow(ctx, getInstallmentTransactionByID, id)
	var i GetInstallmentTransactionByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Value,
		&i.InitialDate,
		&i.FinalDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryID,
		&i.CategoryTransactionType,
		&i.CategoryName,
		&i.CategoryIcon,
		&i.CategoryCreatedAt,
		&i.CategoryUpdatedAt,
		&i.CreditcardID,
		&i.CreditcardName,
		&i.CreditcardFirstFourNumbers,
		&i.CreditcardCreditLimit,
		&i.CreditcardCloseDay,
		&i.CreditcardExpireDay,
		&i.CreditcardBackgroundColor,
		&i.CreditcardTextColor,
		&i.CreditcardCreatedAt,
		&i.CreditcardUpdatedAt,
	)
	return i, err
}

const getShortInstallmentTransactionByID = `-- name: GetShortInstallmentTransactionByID :one
SELECT id, user_id, name, value, initial_date, final_date, category_id, credit_card_id, created_at, updated_at
FROM installment_transactions
WHERE id = $1
`

func (q *Queries) GetShortInstallmentTransactionByID(ctx context.Context, id uuid.UUID) (InstallmentTransaction, error) {
	row := q.db.QueryRow(ctx, getShortInstallmentTransactionByID, id)
	var i InstallmentTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Value,
		&i.InitialDate,
		&i.FinalDate,
		&i.CategoryID,
		&i.CreditCardID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInstallmentTransactionsByUserIDPaginated = `-- name: ListInstallmentTransactionsByUserIDPaginated :many
SELECT 
    it.id,
    it.user_id, 
    it.name, 
    it.value,
    it.initial_date, 
    it.final_date,
    it.created_at, 
    it.updated_at,

    c.id as category_id, 
    c.transaction_type as category_transaction_type, 
    c.name as category_name, 
    c.icon as category_icon,
    c.created_at as category_created_at,
    c.updated_at as category_updated_at,

    cc.id as creditcard_id, 
    cc.name as creditcard_name, 
    cc.first_four_numbers as creditcard_first_four_numbers, 
    cc.credit_limit as creditcard_credit_limit, 
    cc.close_day as creditcard_close_day, 
    cc.expire_day as creditcard_expire_day, 
    cc.background_color as creditcard_background_color, 
    cc.text_color as creditcard_text_color,
    cc.created_at as creditcard_created_at,
    cc.updated_at as creditcard_updated_at,

    COUNT(*) OVER() as total_count
FROM installment_transactions it
LEFT JOIN categories c ON it.category_id = c.id
LEFT JOIN credit_cards cc ON it.credit_card_id = cc.id
WHERE it.user_id = $1
ORDER BY it.initial_date ASC, it.final_date ASC
LIMIT $2 OFFSET $3
`

type ListInstallmentTransactionsByUserIDPaginatedParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListInstallmentTransactionsByUserIDPaginatedRow struct {
	ID                         uuid.UUID          `json:"id"`
	UserID                     uuid.UUID          `json:"user_id"`
	Name                       string             `json:"name"`
	Value                      pgtype.Numeric     `json:"value"`
	InitialDate                pgtype.Timestamptz `json:"initial_date"`
	FinalDate                  pgtype.Timestamptz `json:"final_date"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	CategoryID                 pgtype.UUID        `json:"category_id"`
	CategoryTransactionType    pgtype.Int4        `json:"category_transaction_type"`
	CategoryName               pgtype.Text        `json:"category_name"`
	CategoryIcon               pgtype.Text        `json:"category_icon"`
	CategoryCreatedAt          pgtype.Timestamptz `json:"category_created_at"`
	CategoryUpdatedAt          pgtype.Timestamptz `json:"category_updated_at"`
	CreditcardID               pgtype.UUID        `json:"creditcard_id"`
	CreditcardName             pgtype.Text        `json:"creditcard_name"`
	CreditcardFirstFourNumbers pgtype.Text        `json:"creditcard_first_four_numbers"`
	CreditcardCreditLimit      pgtype.Float8      `json:"creditcard_credit_limit"`
	CreditcardCloseDay         pgtype.Int4        `json:"creditcard_close_day"`
	CreditcardExpireDay        pgtype.Int4        `json:"creditcard_expire_day"`
	CreditcardBackgroundColor  pgtype.Text        `json:"creditcard_background_color"`
	CreditcardTextColor        pgtype.Text        `json:"creditcard_text_color"`
	CreditcardCreatedAt        pgtype.Timestamptz `json:"creditcard_created_at"`
	CreditcardUpdatedAt        pgtype.Timestamptz `json:"creditcard_updated_at"`
	TotalCount                 int64              `json:"total_count"`
}

func (q *Queries) ListInstallmentTransactionsByUserIDPaginated(ctx context.Context, arg ListInstallmentTransactionsByUserIDPaginatedParams) ([]ListInstallmentTransactionsByUserIDPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listInstallmentTransactionsByUserIDPaginated, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInstallmentTransactionsByUserIDPaginatedRow
	for rows.Next() {
		var i ListInstallmentTransactionsByUserIDPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Value,
			&i.InitialDate,
			&i.FinalDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryID,
			&i.CategoryTransactionType,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.CategoryCreatedAt,
			&i.CategoryUpdatedAt,
			&i.CreditcardID,
			&i.CreditcardName,
			&i.CreditcardFirstFourNumbers,
			&i.CreditcardCreditLimit,
			&i.CreditcardCloseDay,
			&i.CreditcardExpireDay,
			&i.CreditcardBackgroundColor,
			&i.CreditcardTextColor,
			&i.CreditcardCreatedAt,
			&i.CreditcardUpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInstallmentTransaction = `-- name: UpdateInstallmentTransaction :one
UPDATE installment_transactions
SET
    name = $2,
    value = $3,
    initial_date = $4,
    final_date = $5,
    category_id = $6,
    credit_card_id = $7,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, value, initial_date, final_date, category_id, credit_card_id, created_at, updated_at
`

type UpdateInstallmentTransactionParams struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	Value        pgtype.Numeric     `json:"value"`
	InitialDate  pgtype.Timestamptz `json:"initial_date"`
	FinalDate    pgtype.Timestamptz `json:"final_date"`
	CategoryID   uuid.UUID          `json:"category_id"`
	CreditCardID pgtype.UUID        `json:"credit_card_id"`
}

func (q *Queries) UpdateInstallmentTransaction(ctx context.Context, arg UpdateInstallmentTransactionParams) (InstallmentTransaction, error) {
	row := q.db.QueryRow(ctx, updateInstallmentTransaction,
		arg.ID,
		arg.Name,
		arg.Value,
		arg.InitialDate,
		arg.FinalDate,
		arg.CategoryID,
		arg.CreditCardID,
	)
	var i InstallmentTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Value,
		&i.InitialDate,
		&i.FinalDate,
		&i.CategoryID,
		&i.CreditCardID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
