// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    user_id,
    name,
    date,
    value,
    paid,
    category_id,
    credit_card_id,
    monthly_transactions_id,
    annual_transactions_id,
    installment_transactions_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, name, date, value, paid, created_at, updated_at
`

type CreateTransactionParams struct {
	UserID                    uuid.UUID          `json:"user_id"`
	Name                      string             `json:"name"`
	Date                      pgtype.Timestamptz `json:"date"`
	Value                     pgtype.Numeric     `json:"value"`
	Paid                      bool               `json:"paid"`
	CategoryID                uuid.UUID          `json:"category_id"`
	CreditCardID              pgtype.UUID        `json:"credit_card_id"`
	MonthlyTransactionsID     pgtype.UUID        `json:"monthly_transactions_id"`
	AnnualTransactionsID      pgtype.UUID        `json:"annual_transactions_id"`
	InstallmentTransactionsID pgtype.UUID        `json:"installment_transactions_id"`
}

type CreateTransactionRow struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Date      pgtype.Timestamptz `json:"date"`
	Value     pgtype.Numeric     `json:"value"`
	Paid      bool               `json:"paid"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (CreateTransactionRow, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.Name,
		arg.Date,
		arg.Value,
		arg.Paid,
		arg.CategoryID,
		arg.CreditCardID,
		arg.MonthlyTransactionsID,
		arg.AnnualTransactionsID,
		arg.InstallmentTransactionsID,
	)
	var i CreateTransactionRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Date,
		&i.Value,
		&i.Paid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions
WHERE id = $1
`

func (q *Queries) DeleteTransaction(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTransaction, id)
	return err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT 
    t.id,
    t.user_id, 
    t.name, 
    t.date, 
    t.value,
    t.paid,
    t.created_at, 
    t.updated_at,

    c.id as category_id, 
    c.transaction_type as category_transaction_type, 
    c.name as category_name, 
    c.icon as category_icon,
    c.created_at as category_created_at,
    c.updated_at as category_updated_at,

    cc.id as creditcard_id, 
    cc.name as creditcard_name, 
    cc.first_four_numbers as creditcard_first_four_numbers, 
    cc.credit_limit as creditcard_credit_limit, 
    cc.close_day as creditcard_close_day, 
    cc.expire_day as creditcard_expire_day, 
    cc.background_color as creditcard_background_color, 
    cc.text_color as creditcard_text_color,
    cc.created_at as creditcard_created_at,
    cc.updated_at as creditcard_updated_at,

    mt.id as monthly_transactions_id, 
    mt.day as monthly_transactions_day,
    mt.name as monthly_transactions_name,
    mt.value as monthly_transactions_value,
    mt.created_at as monthly_transactions_created_at,
    mt.updated_at as monthly_transactions_updated_at,

    at.id as annual_transactions_id, 
    at.month as annual_transactions_month, 
    at.day as annual_transactions_day,
    at.name as annual_transactions_name,
    at.value as annual_transactions_value,
    at.created_at as annual_transactions_created_at,
    at.updated_at as annual_transactions_updated_at,

    it.id as installment_transactions_id, 
    it.name as installment_transactions_name,
    it.value as installment_transactions_value,
    it.initial_date as installment_transactions_initial_date,  
    it.final_date as installment_transactions_final_date,
    it.created_at as installment_transactions_created_at,
    it.updated_at as installment_transactions_updated_at
FROM transactions t
LEFT JOIN categories c ON t.category_id = c.id
LEFT JOIN credit_cards cc ON t.credit_card_id = cc.id
LEFT JOIN monthly_transactions mt ON t.monthly_transactions_id = mt.id
LEFT JOIN annual_transactions at ON t.annual_transactions_id = at.id
LEFT JOIN installment_transactions it ON t.installment_transactions_id = it.id
WHERE t.id = $1
`

type GetTransactionByIDRow struct {
	ID                                 uuid.UUID          `json:"id"`
	UserID                             uuid.UUID          `json:"user_id"`
	Name                               string             `json:"name"`
	Date                               pgtype.Timestamptz `json:"date"`
	Value                              pgtype.Numeric     `json:"value"`
	Paid                               bool               `json:"paid"`
	CreatedAt                          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                          pgtype.Timestamptz `json:"updated_at"`
	CategoryID                         pgtype.UUID        `json:"category_id"`
	CategoryTransactionType            pgtype.Int4        `json:"category_transaction_type"`
	CategoryName                       pgtype.Text        `json:"category_name"`
	CategoryIcon                       pgtype.Text        `json:"category_icon"`
	CategoryCreatedAt                  pgtype.Timestamptz `json:"category_created_at"`
	CategoryUpdatedAt                  pgtype.Timestamptz `json:"category_updated_at"`
	CreditcardID                       pgtype.UUID        `json:"creditcard_id"`
	CreditcardName                     pgtype.Text        `json:"creditcard_name"`
	CreditcardFirstFourNumbers         pgtype.Text        `json:"creditcard_first_four_numbers"`
	CreditcardCreditLimit              pgtype.Float8      `json:"creditcard_credit_limit"`
	CreditcardCloseDay                 pgtype.Int4        `json:"creditcard_close_day"`
	CreditcardExpireDay                pgtype.Int4        `json:"creditcard_expire_day"`
	CreditcardBackgroundColor          pgtype.Text        `json:"creditcard_background_color"`
	CreditcardTextColor                pgtype.Text        `json:"creditcard_text_color"`
	CreditcardCreatedAt                pgtype.Timestamptz `json:"creditcard_created_at"`
	CreditcardUpdatedAt                pgtype.Timestamptz `json:"creditcard_updated_at"`
	MonthlyTransactionsID              pgtype.UUID        `json:"monthly_transactions_id"`
	MonthlyTransactionsDay             pgtype.Int4        `json:"monthly_transactions_day"`
	MonthlyTransactionsName            pgtype.Text        `json:"monthly_transactions_name"`
	MonthlyTransactionsValue           pgtype.Numeric     `json:"monthly_transactions_value"`
	MonthlyTransactionsCreatedAt       pgtype.Timestamptz `json:"monthly_transactions_created_at"`
	MonthlyTransactionsUpdatedAt       pgtype.Timestamptz `json:"monthly_transactions_updated_at"`
	AnnualTransactionsID               pgtype.UUID        `json:"annual_transactions_id"`
	AnnualTransactionsMonth            pgtype.Int4        `json:"annual_transactions_month"`
	AnnualTransactionsDay              pgtype.Int4        `json:"annual_transactions_day"`
	AnnualTransactionsName             pgtype.Text        `json:"annual_transactions_name"`
	AnnualTransactionsValue            pgtype.Numeric     `json:"annual_transactions_value"`
	AnnualTransactionsCreatedAt        pgtype.Timestamptz `json:"annual_transactions_created_at"`
	AnnualTransactionsUpdatedAt        pgtype.Timestamptz `json:"annual_transactions_updated_at"`
	InstallmentTransactionsID          pgtype.UUID        `json:"installment_transactions_id"`
	InstallmentTransactionsName        pgtype.Text        `json:"installment_transactions_name"`
	InstallmentTransactionsValue       pgtype.Numeric     `json:"installment_transactions_value"`
	InstallmentTransactionsInitialDate pgtype.Timestamptz `json:"installment_transactions_initial_date"`
	InstallmentTransactionsFinalDate   pgtype.Timestamptz `json:"installment_transactions_final_date"`
	InstallmentTransactionsCreatedAt   pgtype.Timestamptz `json:"installment_transactions_created_at"`
	InstallmentTransactionsUpdatedAt   pgtype.Timestamptz `json:"installment_transactions_updated_at"`
}

func (q *Queries) GetTransactionByID(ctx context.Context, id uuid.UUID) (GetTransactionByIDRow, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i GetTransactionByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Date,
		&i.Value,
		&i.Paid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryID,
		&i.CategoryTransactionType,
		&i.CategoryName,
		&i.CategoryIcon,
		&i.CategoryCreatedAt,
		&i.CategoryUpdatedAt,
		&i.CreditcardID,
		&i.CreditcardName,
		&i.CreditcardFirstFourNumbers,
		&i.CreditcardCreditLimit,
		&i.CreditcardCloseDay,
		&i.CreditcardExpireDay,
		&i.CreditcardBackgroundColor,
		&i.CreditcardTextColor,
		&i.CreditcardCreatedAt,
		&i.CreditcardUpdatedAt,
		&i.MonthlyTransactionsID,
		&i.MonthlyTransactionsDay,
		&i.MonthlyTransactionsName,
		&i.MonthlyTransactionsValue,
		&i.MonthlyTransactionsCreatedAt,
		&i.MonthlyTransactionsUpdatedAt,
		&i.AnnualTransactionsID,
		&i.AnnualTransactionsMonth,
		&i.AnnualTransactionsDay,
		&i.AnnualTransactionsName,
		&i.AnnualTransactionsValue,
		&i.AnnualTransactionsCreatedAt,
		&i.AnnualTransactionsUpdatedAt,
		&i.InstallmentTransactionsID,
		&i.InstallmentTransactionsName,
		&i.InstallmentTransactionsValue,
		&i.InstallmentTransactionsInitialDate,
		&i.InstallmentTransactionsFinalDate,
		&i.InstallmentTransactionsCreatedAt,
		&i.InstallmentTransactionsUpdatedAt,
	)
	return i, err
}

const hasTransactionsByCategory = `-- name: HasTransactionsByCategory :one
SELECT EXISTS(
    SELECT 1 FROM transactions
    WHERE category_id = $1
)
`

func (q *Queries) HasTransactionsByCategory(ctx context.Context, categoryID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasTransactionsByCategory, categoryID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasTransactionsByCreditCard = `-- name: HasTransactionsByCreditCard :one
SELECT EXISTS(
    SELECT 1 FROM transactions
    WHERE credit_card_id = $1
)
`

func (q *Queries) HasTransactionsByCreditCard(ctx context.Context, creditCardID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasTransactionsByCreditCard, creditCardID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listTransactionsByUserAndDate = `-- name: ListTransactionsByUserAndDate :many
SELECT 
    t.id,
    t.user_id, 
    t.name, 
    t.date, 
    t.value,
    t.paid, 
    t.created_at, 
    t.updated_at,

    c.id as category_id, 
    c.transaction_type as category_transaction_type, 
    c.name as category_name, 
    c.icon as category_icon,
    c.created_at as category_created_at,
    c.updated_at as category_updated_at,

    cc.id as creditcard_id, 
    cc.name as creditcard_name, 
    cc.first_four_numbers as creditcard_first_four_numbers, 
    cc.credit_limit as creditcard_credit_limit, 
    cc.close_day as creditcard_close_day, 
    cc.expire_day as creditcard_expire_day, 
    cc.background_color as creditcard_background_color, 
    cc.text_color as creditcard_text_color,
    cc.created_at as creditcard_created_at,
    cc.updated_at as creditcard_updated_at,

    mt.id as monthly_transactions_id, 
    mt.day as monthly_transactions_day,
    mt.name as monthly_transactions_name,
    mt.value as monthly_transactions_value,
    mt.created_at as monthly_transactions_created_at,
    mt.updated_at as monthly_transactions_updated_at,

    at.id as annual_transactions_id, 
    at.month as annual_transactions_month, 
    at.day as annual_transactions_day,
    at.name as annual_transactions_name,
    at.value as annual_transactions_value,
    at.created_at as annual_transactions_created_at,
    at.updated_at as annual_transactions_updated_at,

    it.id as installment_transactions_id, 
    it.name as installment_transactions_name,
    it.value as installment_transactions_value,
    it.initial_date as installment_transactions_initial_date,  
    it.final_date as installment_transactions_final_date,
    it.created_at as installment_transactions_created_at,
    it.updated_at as installment_transactions_updated_at,

    COUNT(*) OVER() as total_count
FROM transactions t
LEFT JOIN categories c ON t.category_id = c.id
LEFT JOIN credit_cards cc ON t.credit_card_id = cc.id
LEFT JOIN monthly_transactions mt ON t.monthly_transactions_id = mt.id
LEFT JOIN annual_transactions at ON t.annual_transactions_id = at.id
LEFT JOIN installment_transactions it ON t.installment_transactions_id = it.id
WHERE t.user_id = $1
  AND t.date >= $2
  AND t.date <= $3
ORDER BY t.date DESC
LIMIT $4 OFFSET $5
`

type ListTransactionsByUserAndDateParams struct {
	UserID uuid.UUID          `json:"user_id"`
	Date   pgtype.Timestamptz `json:"date"`
	Date_2 pgtype.Timestamptz `json:"date_2"`
	Limit  int32              `json:"limit"`
	Offset int32              `json:"offset"`
}

type ListTransactionsByUserAndDateRow struct {
	ID                                 uuid.UUID          `json:"id"`
	UserID                             uuid.UUID          `json:"user_id"`
	Name                               string             `json:"name"`
	Date                               pgtype.Timestamptz `json:"date"`
	Value                              pgtype.Numeric     `json:"value"`
	Paid                               bool               `json:"paid"`
	CreatedAt                          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                          pgtype.Timestamptz `json:"updated_at"`
	CategoryID                         pgtype.UUID        `json:"category_id"`
	CategoryTransactionType            pgtype.Int4        `json:"category_transaction_type"`
	CategoryName                       pgtype.Text        `json:"category_name"`
	CategoryIcon                       pgtype.Text        `json:"category_icon"`
	CategoryCreatedAt                  pgtype.Timestamptz `json:"category_created_at"`
	CategoryUpdatedAt                  pgtype.Timestamptz `json:"category_updated_at"`
	CreditcardID                       pgtype.UUID        `json:"creditcard_id"`
	CreditcardName                     pgtype.Text        `json:"creditcard_name"`
	CreditcardFirstFourNumbers         pgtype.Text        `json:"creditcard_first_four_numbers"`
	CreditcardCreditLimit              pgtype.Float8      `json:"creditcard_credit_limit"`
	CreditcardCloseDay                 pgtype.Int4        `json:"creditcard_close_day"`
	CreditcardExpireDay                pgtype.Int4        `json:"creditcard_expire_day"`
	CreditcardBackgroundColor          pgtype.Text        `json:"creditcard_background_color"`
	CreditcardTextColor                pgtype.Text        `json:"creditcard_text_color"`
	CreditcardCreatedAt                pgtype.Timestamptz `json:"creditcard_created_at"`
	CreditcardUpdatedAt                pgtype.Timestamptz `json:"creditcard_updated_at"`
	MonthlyTransactionsID              pgtype.UUID        `json:"monthly_transactions_id"`
	MonthlyTransactionsDay             pgtype.Int4        `json:"monthly_transactions_day"`
	MonthlyTransactionsName            pgtype.Text        `json:"monthly_transactions_name"`
	MonthlyTransactionsValue           pgtype.Numeric     `json:"monthly_transactions_value"`
	MonthlyTransactionsCreatedAt       pgtype.Timestamptz `json:"monthly_transactions_created_at"`
	MonthlyTransactionsUpdatedAt       pgtype.Timestamptz `json:"monthly_transactions_updated_at"`
	AnnualTransactionsID               pgtype.UUID        `json:"annual_transactions_id"`
	AnnualTransactionsMonth            pgtype.Int4        `json:"annual_transactions_month"`
	AnnualTransactionsDay              pgtype.Int4        `json:"annual_transactions_day"`
	AnnualTransactionsName             pgtype.Text        `json:"annual_transactions_name"`
	AnnualTransactionsValue            pgtype.Numeric     `json:"annual_transactions_value"`
	AnnualTransactionsCreatedAt        pgtype.Timestamptz `json:"annual_transactions_created_at"`
	AnnualTransactionsUpdatedAt        pgtype.Timestamptz `json:"annual_transactions_updated_at"`
	InstallmentTransactionsID          pgtype.UUID        `json:"installment_transactions_id"`
	InstallmentTransactionsName        pgtype.Text        `json:"installment_transactions_name"`
	InstallmentTransactionsValue       pgtype.Numeric     `json:"installment_transactions_value"`
	InstallmentTransactionsInitialDate pgtype.Timestamptz `json:"installment_transactions_initial_date"`
	InstallmentTransactionsFinalDate   pgtype.Timestamptz `json:"installment_transactions_final_date"`
	InstallmentTransactionsCreatedAt   pgtype.Timestamptz `json:"installment_transactions_created_at"`
	InstallmentTransactionsUpdatedAt   pgtype.Timestamptz `json:"installment_transactions_updated_at"`
	TotalCount                         int64              `json:"total_count"`
}

func (q *Queries) ListTransactionsByUserAndDate(ctx context.Context, arg ListTransactionsByUserAndDateParams) ([]ListTransactionsByUserAndDateRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsByUserAndDate,
		arg.UserID,
		arg.Date,
		arg.Date_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsByUserAndDateRow
	for rows.Next() {
		var i ListTransactionsByUserAndDateRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Date,
			&i.Value,
			&i.Paid,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryID,
			&i.CategoryTransactionType,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.CategoryCreatedAt,
			&i.CategoryUpdatedAt,
			&i.CreditcardID,
			&i.CreditcardName,
			&i.CreditcardFirstFourNumbers,
			&i.CreditcardCreditLimit,
			&i.CreditcardCloseDay,
			&i.CreditcardExpireDay,
			&i.CreditcardBackgroundColor,
			&i.CreditcardTextColor,
			&i.CreditcardCreatedAt,
			&i.CreditcardUpdatedAt,
			&i.MonthlyTransactionsID,
			&i.MonthlyTransactionsDay,
			&i.MonthlyTransactionsName,
			&i.MonthlyTransactionsValue,
			&i.MonthlyTransactionsCreatedAt,
			&i.MonthlyTransactionsUpdatedAt,
			&i.AnnualTransactionsID,
			&i.AnnualTransactionsMonth,
			&i.AnnualTransactionsDay,
			&i.AnnualTransactionsName,
			&i.AnnualTransactionsValue,
			&i.AnnualTransactionsCreatedAt,
			&i.AnnualTransactionsUpdatedAt,
			&i.InstallmentTransactionsID,
			&i.InstallmentTransactionsName,
			&i.InstallmentTransactionsValue,
			&i.InstallmentTransactionsInitialDate,
			&i.InstallmentTransactionsFinalDate,
			&i.InstallmentTransactionsCreatedAt,
			&i.InstallmentTransactionsUpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByUserAndMonthYearPaginated = `-- name: ListTransactionsByUserAndMonthYearPaginated :many
SELECT 
    t.id,
    t.user_id, 
    t.name, 
    t.date, 
    t.value,
    t.paid, 
    t.created_at, 
    t.updated_at,

    c.id as category_id, 
    c.transaction_type as category_transaction_type, 
    c.name as category_name, 
    c.icon as category_icon,
    c.created_at as category_created_at,
    c.updated_at as category_updated_at,

    cc.id as creditcard_id, 
    cc.name as creditcard_name, 
    cc.first_four_numbers as creditcard_first_four_numbers, 
    cc.credit_limit as creditcard_credit_limit, 
    cc.close_day as creditcard_close_day, 
    cc.expire_day as creditcard_expire_day, 
    cc.background_color as creditcard_background_color, 
    cc.text_color as creditcard_text_color,
    cc.created_at as creditcard_created_at,
    cc.updated_at as creditcard_updated_at,

    mt.id as monthly_transactions_id, 
    mt.day as monthly_transactions_day,
    mt.name as monthly_transactions_name,
    mt.value as monthly_transactions_value,
    mt.created_at as monthly_transactions_created_at,
    mt.updated_at as monthly_transactions_updated_at,

    at.id as annual_transactions_id, 
    at.month as annual_transactions_month, 
    at.day as annual_transactions_day,
    at.name as annual_transactions_name,
    at.value as annual_transactions_value,
    at.created_at as annual_transactions_created_at,
    at.updated_at as annual_transactions_updated_at,

    it.id as installment_transactions_id, 
    it.name as installment_transactions_name,
    it.value as installment_transactions_value,
    it.initial_date as installment_transactions_initial_date,  
    it.final_date as installment_transactions_final_date,
    it.created_at as installment_transactions_created_at,
    it.updated_at as installment_transactions_updated_at,

    COUNT(*) OVER() as total_count
FROM transactions t
LEFT JOIN categories c ON t.category_id = c.id
LEFT JOIN credit_cards cc ON t.credit_card_id = cc.id
LEFT JOIN monthly_transactions mt ON t.monthly_transactions_id = mt.id
LEFT JOIN annual_transactions at ON t.annual_transactions_id = at.id
LEFT JOIN installment_transactions it ON t.installment_transactions_id = it.id
WHERE t.user_id = $1
  AND (
      (
          c.transaction_type IN (0, 1)
          AND EXTRACT(YEAR FROM t.date) = $2::int
          AND EXTRACT(MONTH FROM t.date) = $3::int
      )
      OR
      (
          c.transaction_type = 2
          AND t.credit_card_id IS NOT NULL
          AND t.date > (
              make_date($2::int, $3::int, 1) - INTERVAL '2 months' + (cc.close_day || ' days')::INTERVAL
          )
          AND t.date <= (
              make_date($2::int, $3::int, 1) - INTERVAL '1 month' + (cc.close_day || ' days')::INTERVAL
          )
      )
  )
ORDER BY t.date DESC
LIMIT $5 OFFSET $4
`

type ListTransactionsByUserAndMonthYearPaginatedParams struct {
	UserID     uuid.UUID `json:"user_id"`
	Year       int32     `json:"year"`
	Month      int32     `json:"month"`
	PageOffset int32     `json:"page_offset"`
	PageLimit  int32     `json:"page_limit"`
}

type ListTransactionsByUserAndMonthYearPaginatedRow struct {
	ID                                 uuid.UUID          `json:"id"`
	UserID                             uuid.UUID          `json:"user_id"`
	Name                               string             `json:"name"`
	Date                               pgtype.Timestamptz `json:"date"`
	Value                              pgtype.Numeric     `json:"value"`
	Paid                               bool               `json:"paid"`
	CreatedAt                          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                          pgtype.Timestamptz `json:"updated_at"`
	CategoryID                         pgtype.UUID        `json:"category_id"`
	CategoryTransactionType            pgtype.Int4        `json:"category_transaction_type"`
	CategoryName                       pgtype.Text        `json:"category_name"`
	CategoryIcon                       pgtype.Text        `json:"category_icon"`
	CategoryCreatedAt                  pgtype.Timestamptz `json:"category_created_at"`
	CategoryUpdatedAt                  pgtype.Timestamptz `json:"category_updated_at"`
	CreditcardID                       pgtype.UUID        `json:"creditcard_id"`
	CreditcardName                     pgtype.Text        `json:"creditcard_name"`
	CreditcardFirstFourNumbers         pgtype.Text        `json:"creditcard_first_four_numbers"`
	CreditcardCreditLimit              pgtype.Float8      `json:"creditcard_credit_limit"`
	CreditcardCloseDay                 pgtype.Int4        `json:"creditcard_close_day"`
	CreditcardExpireDay                pgtype.Int4        `json:"creditcard_expire_day"`
	CreditcardBackgroundColor          pgtype.Text        `json:"creditcard_background_color"`
	CreditcardTextColor                pgtype.Text        `json:"creditcard_text_color"`
	CreditcardCreatedAt                pgtype.Timestamptz `json:"creditcard_created_at"`
	CreditcardUpdatedAt                pgtype.Timestamptz `json:"creditcard_updated_at"`
	MonthlyTransactionsID              pgtype.UUID        `json:"monthly_transactions_id"`
	MonthlyTransactionsDay             pgtype.Int4        `json:"monthly_transactions_day"`
	MonthlyTransactionsName            pgtype.Text        `json:"monthly_transactions_name"`
	MonthlyTransactionsValue           pgtype.Numeric     `json:"monthly_transactions_value"`
	MonthlyTransactionsCreatedAt       pgtype.Timestamptz `json:"monthly_transactions_created_at"`
	MonthlyTransactionsUpdatedAt       pgtype.Timestamptz `json:"monthly_transactions_updated_at"`
	AnnualTransactionsID               pgtype.UUID        `json:"annual_transactions_id"`
	AnnualTransactionsMonth            pgtype.Int4        `json:"annual_transactions_month"`
	AnnualTransactionsDay              pgtype.Int4        `json:"annual_transactions_day"`
	AnnualTransactionsName             pgtype.Text        `json:"annual_transactions_name"`
	AnnualTransactionsValue            pgtype.Numeric     `json:"annual_transactions_value"`
	AnnualTransactionsCreatedAt        pgtype.Timestamptz `json:"annual_transactions_created_at"`
	AnnualTransactionsUpdatedAt        pgtype.Timestamptz `json:"annual_transactions_updated_at"`
	InstallmentTransactionsID          pgtype.UUID        `json:"installment_transactions_id"`
	InstallmentTransactionsName        pgtype.Text        `json:"installment_transactions_name"`
	InstallmentTransactionsValue       pgtype.Numeric     `json:"installment_transactions_value"`
	InstallmentTransactionsInitialDate pgtype.Timestamptz `json:"installment_transactions_initial_date"`
	InstallmentTransactionsFinalDate   pgtype.Timestamptz `json:"installment_transactions_final_date"`
	InstallmentTransactionsCreatedAt   pgtype.Timestamptz `json:"installment_transactions_created_at"`
	InstallmentTransactionsUpdatedAt   pgtype.Timestamptz `json:"installment_transactions_updated_at"`
	TotalCount                         int64              `json:"total_count"`
}

func (q *Queries) ListTransactionsByUserAndMonthYearPaginated(ctx context.Context, arg ListTransactionsByUserAndMonthYearPaginatedParams) ([]ListTransactionsByUserAndMonthYearPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsByUserAndMonthYearPaginated,
		arg.UserID,
		arg.Year,
		arg.Month,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsByUserAndMonthYearPaginatedRow
	for rows.Next() {
		var i ListTransactionsByUserAndMonthYearPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Date,
			&i.Value,
			&i.Paid,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryID,
			&i.CategoryTransactionType,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.CategoryCreatedAt,
			&i.CategoryUpdatedAt,
			&i.CreditcardID,
			&i.CreditcardName,
			&i.CreditcardFirstFourNumbers,
			&i.CreditcardCreditLimit,
			&i.CreditcardCloseDay,
			&i.CreditcardExpireDay,
			&i.CreditcardBackgroundColor,
			&i.CreditcardTextColor,
			&i.CreditcardCreatedAt,
			&i.CreditcardUpdatedAt,
			&i.MonthlyTransactionsID,
			&i.MonthlyTransactionsDay,
			&i.MonthlyTransactionsName,
			&i.MonthlyTransactionsValue,
			&i.MonthlyTransactionsCreatedAt,
			&i.MonthlyTransactionsUpdatedAt,
			&i.AnnualTransactionsID,
			&i.AnnualTransactionsMonth,
			&i.AnnualTransactionsDay,
			&i.AnnualTransactionsName,
			&i.AnnualTransactionsValue,
			&i.AnnualTransactionsCreatedAt,
			&i.AnnualTransactionsUpdatedAt,
			&i.InstallmentTransactionsID,
			&i.InstallmentTransactionsName,
			&i.InstallmentTransactionsValue,
			&i.InstallmentTransactionsInitialDate,
			&i.InstallmentTransactionsFinalDate,
			&i.InstallmentTransactionsCreatedAt,
			&i.InstallmentTransactionsUpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByUserIDPaginated = `-- name: ListTransactionsByUserIDPaginated :many
SELECT 
    t.id,
    t.user_id, 
    t.name, 
    t.date, 
    t.value,
    t.paid, 
    t.created_at, 
    t.updated_at,

    c.id as category_id, 
    c.transaction_type as category_transaction_type, 
    c.name as category_name, 
    c.icon as category_icon,
    c.created_at as category_created_at,
    c.updated_at as category_updated_at,

    cc.id as creditcard_id, 
    cc.name as creditcard_name, 
    cc.first_four_numbers as creditcard_first_four_numbers, 
    cc.credit_limit as creditcard_credit_limit, 
    cc.close_day as creditcard_close_day, 
    cc.expire_day as creditcard_expire_day, 
    cc.background_color as creditcard_background_color, 
    cc.text_color as creditcard_text_color,
    cc.created_at as creditcard_created_at,
    cc.updated_at as creditcard_updated_at,

    mt.id as monthly_transactions_id, 
    mt.day as monthly_transactions_day,
    mt.name as monthly_transactions_name,
    mt.value as monthly_transactions_value,
    mt.created_at as monthly_transactions_created_at,
    mt.updated_at as monthly_transactions_updated_at,

    at.id as annual_transactions_id, 
    at.month as annual_transactions_month, 
    at.day as annual_transactions_day,
    at.name as annual_transactions_name,
    at.value as annual_transactions_value,
    at.created_at as annual_transactions_created_at,
    at.updated_at as annual_transactions_updated_at,

    it.id as installment_transactions_id, 
    it.name as installment_transactions_name,
    it.value as installment_transactions_value,
    it.initial_date as installment_transactions_initial_date,  
    it.final_date as installment_transactions_final_date,
    it.created_at as installment_transactions_created_at,
    it.updated_at as installment_transactions_updated_at,

    COUNT(*) OVER() as total_count
FROM transactions t
LEFT JOIN categories c ON t.category_id = c.id
LEFT JOIN credit_cards cc ON t.credit_card_id = cc.id
LEFT JOIN monthly_transactions mt ON t.monthly_transactions_id = mt.id
LEFT JOIN annual_transactions at ON t.annual_transactions_id = at.id
LEFT JOIN installment_transactions it ON t.installment_transactions_id = it.id
WHERE t.user_id = $1
ORDER BY t.date DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsByUserIDPaginatedParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListTransactionsByUserIDPaginatedRow struct {
	ID                                 uuid.UUID          `json:"id"`
	UserID                             uuid.UUID          `json:"user_id"`
	Name                               string             `json:"name"`
	Date                               pgtype.Timestamptz `json:"date"`
	Value                              pgtype.Numeric     `json:"value"`
	Paid                               bool               `json:"paid"`
	CreatedAt                          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                          pgtype.Timestamptz `json:"updated_at"`
	CategoryID                         pgtype.UUID        `json:"category_id"`
	CategoryTransactionType            pgtype.Int4        `json:"category_transaction_type"`
	CategoryName                       pgtype.Text        `json:"category_name"`
	CategoryIcon                       pgtype.Text        `json:"category_icon"`
	CategoryCreatedAt                  pgtype.Timestamptz `json:"category_created_at"`
	CategoryUpdatedAt                  pgtype.Timestamptz `json:"category_updated_at"`
	CreditcardID                       pgtype.UUID        `json:"creditcard_id"`
	CreditcardName                     pgtype.Text        `json:"creditcard_name"`
	CreditcardFirstFourNumbers         pgtype.Text        `json:"creditcard_first_four_numbers"`
	CreditcardCreditLimit              pgtype.Float8      `json:"creditcard_credit_limit"`
	CreditcardCloseDay                 pgtype.Int4        `json:"creditcard_close_day"`
	CreditcardExpireDay                pgtype.Int4        `json:"creditcard_expire_day"`
	CreditcardBackgroundColor          pgtype.Text        `json:"creditcard_background_color"`
	CreditcardTextColor                pgtype.Text        `json:"creditcard_text_color"`
	CreditcardCreatedAt                pgtype.Timestamptz `json:"creditcard_created_at"`
	CreditcardUpdatedAt                pgtype.Timestamptz `json:"creditcard_updated_at"`
	MonthlyTransactionsID              pgtype.UUID        `json:"monthly_transactions_id"`
	MonthlyTransactionsDay             pgtype.Int4        `json:"monthly_transactions_day"`
	MonthlyTransactionsName            pgtype.Text        `json:"monthly_transactions_name"`
	MonthlyTransactionsValue           pgtype.Numeric     `json:"monthly_transactions_value"`
	MonthlyTransactionsCreatedAt       pgtype.Timestamptz `json:"monthly_transactions_created_at"`
	MonthlyTransactionsUpdatedAt       pgtype.Timestamptz `json:"monthly_transactions_updated_at"`
	AnnualTransactionsID               pgtype.UUID        `json:"annual_transactions_id"`
	AnnualTransactionsMonth            pgtype.Int4        `json:"annual_transactions_month"`
	AnnualTransactionsDay              pgtype.Int4        `json:"annual_transactions_day"`
	AnnualTransactionsName             pgtype.Text        `json:"annual_transactions_name"`
	AnnualTransactionsValue            pgtype.Numeric     `json:"annual_transactions_value"`
	AnnualTransactionsCreatedAt        pgtype.Timestamptz `json:"annual_transactions_created_at"`
	AnnualTransactionsUpdatedAt        pgtype.Timestamptz `json:"annual_transactions_updated_at"`
	InstallmentTransactionsID          pgtype.UUID        `json:"installment_transactions_id"`
	InstallmentTransactionsName        pgtype.Text        `json:"installment_transactions_name"`
	InstallmentTransactionsValue       pgtype.Numeric     `json:"installment_transactions_value"`
	InstallmentTransactionsInitialDate pgtype.Timestamptz `json:"installment_transactions_initial_date"`
	InstallmentTransactionsFinalDate   pgtype.Timestamptz `json:"installment_transactions_final_date"`
	InstallmentTransactionsCreatedAt   pgtype.Timestamptz `json:"installment_transactions_created_at"`
	InstallmentTransactionsUpdatedAt   pgtype.Timestamptz `json:"installment_transactions_updated_at"`
	TotalCount                         int64              `json:"total_count"`
}

func (q *Queries) ListTransactionsByUserIDPaginated(ctx context.Context, arg ListTransactionsByUserIDPaginatedParams) ([]ListTransactionsByUserIDPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsByUserIDPaginated, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsByUserIDPaginatedRow
	for rows.Next() {
		var i ListTransactionsByUserIDPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Date,
			&i.Value,
			&i.Paid,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryID,
			&i.CategoryTransactionType,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.CategoryCreatedAt,
			&i.CategoryUpdatedAt,
			&i.CreditcardID,
			&i.CreditcardName,
			&i.CreditcardFirstFourNumbers,
			&i.CreditcardCreditLimit,
			&i.CreditcardCloseDay,
			&i.CreditcardExpireDay,
			&i.CreditcardBackgroundColor,
			&i.CreditcardTextColor,
			&i.CreditcardCreatedAt,
			&i.CreditcardUpdatedAt,
			&i.MonthlyTransactionsID,
			&i.MonthlyTransactionsDay,
			&i.MonthlyTransactionsName,
			&i.MonthlyTransactionsValue,
			&i.MonthlyTransactionsCreatedAt,
			&i.MonthlyTransactionsUpdatedAt,
			&i.AnnualTransactionsID,
			&i.AnnualTransactionsMonth,
			&i.AnnualTransactionsDay,
			&i.AnnualTransactionsName,
			&i.AnnualTransactionsValue,
			&i.AnnualTransactionsCreatedAt,
			&i.AnnualTransactionsUpdatedAt,
			&i.InstallmentTransactionsID,
			&i.InstallmentTransactionsName,
			&i.InstallmentTransactionsValue,
			&i.InstallmentTransactionsInitialDate,
			&i.InstallmentTransactionsFinalDate,
			&i.InstallmentTransactionsCreatedAt,
			&i.InstallmentTransactionsUpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const payTransaction = `-- name: PayTransaction :exec
UPDATE transactions
SET
    paid = $2,
    updated_at = NOW()
WHERE id = $1
`

type PayTransactionParams struct {
	ID   uuid.UUID `json:"id"`
	Paid bool      `json:"paid"`
}

func (q *Queries) PayTransaction(ctx context.Context, arg PayTransactionParams) error {
	_, err := q.db.Exec(ctx, payTransaction, arg.ID, arg.Paid)
	return err
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET
    name = $2,
    date = $3,
    value = $4,
    paid = $5,
    category_id = $6,
    credit_card_id = $7,
    monthly_transactions_id = $8,
    annual_transactions_id = $9,
    installment_transactions_id = $10,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, date, value, paid, category_id, credit_card_id, monthly_transactions_id, annual_transactions_id, installment_transactions_id, created_at, updated_at
`

type UpdateTransactionParams struct {
	ID                        uuid.UUID          `json:"id"`
	Name                      string             `json:"name"`
	Date                      pgtype.Timestamptz `json:"date"`
	Value                     pgtype.Numeric     `json:"value"`
	Paid                      bool               `json:"paid"`
	CategoryID                uuid.UUID          `json:"category_id"`
	CreditCardID              pgtype.UUID        `json:"credit_card_id"`
	MonthlyTransactionsID     pgtype.UUID        `json:"monthly_transactions_id"`
	AnnualTransactionsID      pgtype.UUID        `json:"annual_transactions_id"`
	InstallmentTransactionsID pgtype.UUID        `json:"installment_transactions_id"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.Name,
		arg.Date,
		arg.Value,
		arg.Paid,
		arg.CategoryID,
		arg.CreditCardID,
		arg.MonthlyTransactionsID,
		arg.AnnualTransactionsID,
		arg.InstallmentTransactionsID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Date,
		&i.Value,
		&i.Paid,
		&i.CategoryID,
		&i.CreditCardID,
		&i.MonthlyTransactionsID,
		&i.AnnualTransactionsID,
		&i.InstallmentTransactionsID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
